// Generated by CoffeeScript 1.8.0
(function() {
  var i, msg, _i, _ref;

  msg = ["Hello", "World"];

  for (i = _i = 0, _ref = msg.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    alert(msg[i]);
    console.log(msg[i]);
  }

}).call(this);
